-- Scripts para criação do projeto --

CREATE TABLE TBVEICULO (
PLACAUF VARCHAR(50) NOT NULL,
CHASSI VARCHAR(50) NOT NULL,
TIPO VARCHAR(50) NOT NULL,
COMBUSTIVEL VARCHAR(50) NOT NULL,
MARCAMODELO VARCHAR(50) NOT NULL,
ANOFAB VARCHAR(50) NOT NULL,
ANOMOD VARCHAR(50) NOT NULL,
COR VARCHAR(50) NOT NULL,
PRIMARY KEY (PLACAUF) 
);



CREATE TABLE TBPECAS (
id int NOT NULL,
CODIGO VARCHAR(50) NOT NULL,
DESCRICAO VARCHAR(50) NOT NULL,
CATEGORIA VARCHAR(50) NOT NULL,
FABRICANTE VARCHAR(50) NOT NULL,
PLACAVEICULO VARCHAR(50) NOT NULL
PRIMARY KEY (ID) 
);